### ISSUE TITLE
Make index for table Files and Folders not unique

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/bcpIntermediateDatabase#27]
Make index for table Files [IX_Files] and Folders [IX_Folders] not unique that IDB.Load.BCP can run without an error.

**Comment by kieninj** [comment]
@MarkusCool 
I agree with removing the [IX_Folders] index.
For the [IX_Files] I would suggest to add column [FolderID] to the index. Without [FolderID] "not unique" filenames were not supported. But in general that index avoids duplicate entries for files. Should we really remove it?

**Comment by kieninj** [comment]
we agreed on keeping the [IX_Files] but adding column [FolderID] to the index

**Comment by MarkusCool** [comment]
When 2 BCP-packages are imported into 1 IDB and there are identical files in the BCP-packages, the tool will stop and hang.
A workaround is to remove the "unique" of the index [IX_Files].
I will put a note to the partner knowledge base.
