### ISSUE TITLE
IDB.Tranfer.BCP must be able to assign files to the root folder

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/bcpIntermediateDatabase#45]
Some files like the Designs.ipj are located in the root folder $ (Project Explorer) of Vault. Therefor it is necessary to have a root folder with a FolderID in the IDB. This FolderID could be set for the file that should be assigned to the folder $.
If this is done manually in the IDB and the IDB is exported with the IDB.Tranfer.BCP an additional sub-folder "$" is currently created below the root folder in the bcp package.
The IDB.Tranfer.BCP should put the files into the <Root> folder that are linked to the folder $ in the IDB.

**Comment by kieninj** [comment]
The following settings in table Folders did already work for being accepted as Vault root folder:
1. <img width="553" alt="Bildschirmfoto 2020-08-13 um 15 39 30" src="https://user-images.githubusercontent.com/34063457/90142524-c4766c80-dd7c-11ea-89d2-5fb3b4bfae54.png">

1. <img width="584" alt="Bildschirmfoto 2020-08-13 um 15 39 11" src="https://user-images.githubusercontent.com/34063457/90142445-aa3c8e80-dd7c-11ea-970f-21936bbb6c15.png">

Now this is also working:
<img width="608" alt="Bildschirmfoto 2020-08-13 um 15 40 26" src="https://user-images.githubusercontent.com/34063457/90142684-f5ef3800-dd7c-11ea-84c9-f1271d5ad72c.png">
