### ISSUE TITLE
Create a tool to analyze Inventor references

### ISSUE THREAD

**Issue by kieninj** [coolOrangeLabs/bcpIntermediateDatabase#7]
In case the the intermediate database does not have file relations yet or the `RefId` field is empty in table `FileFileRelations`, a tool is required to retrieve these RefIds from Inventor.

There are different situations to consider:
- [x] No file references are available yet (`FileFileRelations` empty)
- [x] References are known (`FileFileRelations` empty) but `RefId` is empty (null or -1)

The following types of references should be supported
- [x] Inventor native references
- [x] Inventor OLE references

**Comment by christiangessner** [comment]
just to be clear: if there is no relation in the IDB, it needs to be created. This is not only true for Inventor, but also for AutoCAD #14
